name: ci-cd
on:
  workflow_dispatch:
    inputs:
      build_gateway_image:
        type: boolean
        description: Push Gateway Image
      build_identity_image:
        type: boolean
        description: Push Identity Image
      build_catalog_image:
        type: boolean
        description: Push Catalog Image    
jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
  docker:
    name: Docker Build & Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.event.inputs.build_gateway_image == 'true'
        name: Build Gateway Image
        working-directory: ./
        run: |
          dotnet publish projects/fluentpos-lite/src/api-gateway/Gateway/Gateway.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.gateway --all-tags

      - if: github.event.inputs.build_identity_image == 'true'
        name: Build Identity Server Image
        working-directory: ./
        run: |
          dotnet publish projects/fluentpos-lite/src/identity-server/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.identity
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.identity --all-tags

      - if: github.event.inputs.build_catalog_image == 'true'
        name: Build Catalog Service Image
        working-directory: ./
        run: |
          dotnet publish projects/fluentpos-lite/src/services/catalog/Host/Host.csproj --os linux --arch x64 -c Release -p:PublishProfile=DefaultContainer -p:ContainerImageName=${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.catalog
          docker push ${{ secrets.DOCKER_USERNAME }}/fluentpos-lite.catalog --all-tags
  cleanup:
    name: Cleanup
    needs:
      - docker
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: "Removes Build Artifacts"
        uses: geekyeggo/delete-artifact@v1
        with:
          name: |
            build
            test
            docker
